name: Dev CI (Preview Publish)

on:
  push:
    branches:
      - dev

concurrency:
  group: dev-ci
  cancel-in-progress: true

jobs:
  dev-ci:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
            9.x

      - name: Restore
        run: dotnet restore

      - name: Resolve Preview Version
        id: version
        shell: bash
        run: |
          set -euo pipefail
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.0")
          BASE=${LAST_TAG#v}
          IFS='.' read -r MA MI PA <<<"$BASE"
          NEXT_PATCH=$((PA+1))
          PREVIEW="${MA}.${MI}.${NEXT_PATCH}-preview.${GITHUB_RUN_NUMBER}+sha.$(git rev-parse --short HEAD)"
          echo "Resolved preview version: $PREVIEW"
          echo "VERSION=$PREVIEW" >> $GITHUB_ENV

      - name: Build (Release)
        run: dotnet build -c Release --no-restore -p:Version=${VERSION}

      - name: Test
        run: dotnet test tests/Space.Tests/Space.Tests.csproj -c Release --no-build --logger trx

      - name: Pack
        run: |
          PROJECTS=( \
            src/Space.Abstraction/Space.Abstraction.csproj \
            src/Space.DependencyInjection/Space.DependencyInjection.csproj \
            src/Space.Modules.InMemoryCache/Space.Modules.InMemoryCache.csproj \
          )
          mkdir -p artifacts
          for p in "${PROJECTS[@]}"; do
            echo "Packing $p -> ${VERSION}";
            dotnet pack "$p" -c Release --no-build -p:PackageVersion=${VERSION} -p:Version=${VERSION} -o artifacts
          done

      - name: Publish Preview Packages (NuGet)
        if: success()
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Publish Outputs
        run: |
          mkdir -p drop
          PROJECTS=( \
            src/Space.Abstraction/Space.Abstraction.csproj \
            src/Space.DependencyInjection/Space.DependencyInjection.csproj \
            src/Space.Modules.InMemoryCache/Space.Modules.InMemoryCache.csproj \
          )
          for proj in "${PROJECTS[@]}"; do
            NAME=$(basename "${proj%.*}")
            dotnet publish "$proj" -c Release -o "drop/${NAME}" -p:Version=${VERSION}
          done
          cp artifacts/*.nupkg drop/

      - name: Upload Drop Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-drop
          path: drop

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dev-test-results
          path: '**/*.trx'
