name: Dev CI (Preview Publish)

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version (vX.Y.Z or X.Y.Z). Leave empty to use latest release tag'
        required: false
        type: string

concurrency:
  group: dev-ci
  cancel-in-progress: true

jobs:
  dev-preview:
    # Run when triggered manually OR on prerelease publishes
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'release' && github.event.release.prerelease == true) }}
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
            9.x

      - name: Get Latest Release Tag
        id: latest
        uses: actions/github-script@v7
        with:
            script: |
              const { data } = await github.rest.repos.getLatestRelease({ owner: context.repo.owner, repo: context.repo.repo });
              core.setOutput('tag', data.tag_name);

      - name: Determine Preview Version
        id: version
        shell: bash
        run: |
          set -euo pipefail
          RAW_INPUT="${{ github.event.inputs.release || '' }}"
          RAW_TAG="${{ github.event.release.tag_name || '' }}"
          LATEST_TAG="${{ steps.latest.outputs.tag || '' }}"

          # Pick source tag: user input > release event tag > latest release tag
          SRC_TAG="$RAW_INPUT"
          if [[ -z "$SRC_TAG" ]]; then
            SRC_TAG="$RAW_TAG"
          fi
          if [[ -z "$SRC_TAG" ]]; then
            SRC_TAG="$LATEST_TAG"
          fi
          if [[ -z "$SRC_TAG" ]]; then
            echo "No version provided and no release tag available." >&2
            exit 1
          fi

          # Normalize possible inputs (e.g., refs/tags/v1.0.0, v1.0.0, 1.0.0)
          TAG=$(echo -n "$SRC_TAG" | tr -d '[:space:]')
          TAG=${TAG#refs/tags/}
          TAG=${TAG#tags/}
          # Strip a single leading v or V
          if [[ "$TAG" =~ ^[vV]([0-9].*)$ ]]; then
            BASE_VERSION="${BASH_REMATCH[1]}"
          else
            BASE_VERSION="$TAG"
          fi
          # Basic SemVer (allow pre-release/build metadata)
          if [[ ! "$BASE_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([-.+].*)?$ ]]; then
            echo "Input '$SRC_TAG' produced invalid base version '$BASE_VERSION'. Expected '1.2.3' or 'v1.2.3'." >&2
            exit 1
          fi
          PREVIEW_VERSION="${BASE_VERSION}-preview"
          echo "Using preview version: $PREVIEW_VERSION (source: $SRC_TAG)"
          echo "VERSION=$PREVIEW_VERSION" >> $GITHUB_ENV

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build -c Release --no-restore -p:Version=${VERSION}

      - name: Test
        run: dotnet test tests/Space.Tests/Space.Tests.csproj -c Release --no-build --logger trx

      - name: Pack
        run: |
          PROJECTS=( \
            src/Space.Abstraction/Space.Abstraction.csproj \
            src/Space.DependencyInjection/Space.DependencyInjection.csproj \
          )
          mkdir -p artifacts
          for p in "${PROJECTS[@]}"; do
            echo "Packing $p -> ${VERSION}";
            dotnet pack "$p" -c Release --no-build -p:PackageVersion=${VERSION} -p:Version=${VERSION} -o artifacts
          done

      - name: Publish Preview Packages (NuGet)
        if: success()
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Publish Outputs
        run: |
          mkdir -p drop
          PROJECTS=( \
            src/Space.Abstraction/Space.Abstraction.csproj \
            src/Space.DependencyInjection/Space.DependencyInjection.csproj \
          )
          for proj in "${PROJECTS[@]}"; do
            NAME=$(basename "${proj%.*}")
            dotnet publish "$proj" -c Release -o "drop/${NAME}" -p:Version=${VERSION}
          done
          cp artifacts/*.nupkg drop/

      - name: Upload Drop Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-drop
          path: drop

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dev-test-results
          path: '**/*.trx'
