name: Validation Build

on:
  push:
    branches:
      - 'feature/*'
      - 'features/*'
  pull_request:
    branches:
      - dev
      - master

concurrency:
  group: validation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
            9.x

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build -c Release --no-restore

      - name: Test (Release)
        run: dotnet test tests/Space.Tests/Space.Tests.csproj -c Release --no-build --logger trx

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validation-test-results
          path: '**/*.trx'
